name: TriggerPE
author: alvin0319
main: alvin0319\TriggerPE\TriggerPE
version: 1.0.0
api: 3.0.0

mcpe-protocol: 407

permissions:
  triggerpe.*:
    description: A Main permission of TriggerPE
    children:
      triggerpe.command.*:
        children:
          triggerpe.command.vtc:
            default: op
          triggerpe.command.vtcmd:
            default: op
          triggerpe.command.vta:
            default: op